version: '3.8'

services:
  face-detect-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - face-detect-network
    environment:
      - NODE_ENV=production
      - PORT=3001

networks:
  face-detect-network:
    driver: bridge 